config/routes.rb
Rails.application.routes.draw do
  get "/" => "home#index"
  resources :todos
  resources :users
  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
require "date"
require "active_record"

class Todo < ActiveRecord::Base
  validates :todo_text, presence: true
  validates :due_date, presence: true
  validates :todo_text, length: { minimum: 2 }

  belongs_to :user

  def due_today?
    due_date == Date.today
  end

  def self.of_user(user)
    where(user_id: user.id)
  end

  def self.overdue
    where("completed = ? and due_date < ? ",false,Date.today)
  end

  def self.due_today
    where("due_date = ?",Date.today)
  end

  def self.due_later
    where("due_date > ?",Date.today)
  end

  def self.completed
    where(completed: true)
  end

end

app/models/user.rb
require "active_record"

class User < ActiveRecord::Base
  has_secure_password
  has_many :todos
  validates :first_name, presence: true
  validates :email, { presence: true, uniqueness: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :ensure_user_logged_in
    def ensure_user_logged_in
        unless current_user
            redirect_to "/"
        end
    end
    def current_user
        return @current_user if @current_user
        current_user_id = session[:current_user_id]
        if current_user_id
            @current_user = User.find(current_user_id)
        else
            nil
        end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :ensure_user_logged_in
  def index
    if current_user
      redirect_to todos_path
    else
      render "index"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController  < ApplicationController
    skip_before_action :ensure_user_logged_in

    def new
    end

    def create
        user=User.find_by(email: params[:email])
        if user && user.authenticate(params[:password])
            session[:current_user_id] = user.id
            redirect_to "/"
        else
            flash[:error] = "Your login attempt was invalid ,Please retry."
            redirect_to new_sessions_path

        end
    end

    def destroy
        session[:current_user_id] = nil
        @current_user = nil
        redirect_to "/"
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = current_user.todos
    render "index"
  end
  def show
    id = params[:id]
    todo=current_user.todos.find(id)
    render "todo"
  end
  def create
    todo_text = params[:todo_text]
    due_date = params[:due_date]
    new_to_do =  Todo.new(todo_text: todo_text,
      due_date: due_date,
      completed: false,
    user_id: current_user.id)
    if new_to_do.save
      redirect_to todos_path
    else
      flash[:error] = new_to_do.errors.full_messages.join(", ")
      redirect_to todos_path
    end
  end
  def update
    id = params[:id]
    completed = params[:completed]
    todo =current_user.todos.find(id)
    todo.completed = completed
    todo.save!
    redirect_to todos_path
  end
  def destroy
    id = params[:id]
    todo =current_user.todos.find(id)
    todo.destroy
    redirect_to todos_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def new
    render "users/new"
  end

  def create
    new_user = User.new(
      first_name: params[:first_name],
      last_name: params[:last_name],
      email: params[:email],
      password: params[:password],
    )
    if new_user.save
      redirect_to todos_path
      flash[:success] = "you've signed-up successfully, now please sign-in to continue"
    else
      flash[:error] = new_user.errors.full_messages.join(", ")
      redirect_to "/users/new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1 class="Home-title">
    Welcome to the Todo homepage
</h1>
<h3 class="Home-authenticate">
    If you are a new user,  <%= link_to "sign up here", new_user_path %>
</h3>
<h3 class="Home-authenticate">
    If you are an existing user,  <%= link_to "sign in here", new_sessions_path %>
</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
  </head>
  <body>
    <% if @current_user %>
        <p class="UserHeader">
            Welcome <%= @current_user.first_name %>
            <%= link_to "Sign-out", destroy_session_path, method: "delete" %>
        </p>
    <% end %>
    <% if flash[:error] %>
          <p class="Flash-error">
              <%= flash[:error] %>
          </p>
    <% end %>
    <% if flash[:success] %>
      <p class="Flash-success">
          <%= flash[:success] %>
      </p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/todos/_todo-section.html.erb
<section class="TodoSection">
       <div class="TodoSectionTitle">
          <p class="TodoSectionTitle-text"><%= section_title %></p>
          <p class="TodoSectionTitle-remainingCount"><%= todos.completed.count %> / <%= todos.count %> </p>
        </div>

        <ul>
          <% todos.each do |todo| %>
            <li class="TodoItem">
                <div class="TodoItem-container">
                  <%= form_with(url: "todos/#{todo.id}", method: "put") do %>
                    <%= check_box_tag :completed, "completed", todo.completed ? true : false, onclick: "this.form.submit()" %>
                  <% end %>
                  <p class='<%= todo.completed ? "TodoItem-completedText" : "" %>' >
                    <%= todo.todo_text %>
                  </p>
                  <% if show_due_date %>
                      <p class="TodoItem-dueDate"> <%= todo.due_date.to_s(:short) %> </p>
                  <% end %>
                  <a href="javascript:void(0)" class="TodoItem__DeleteButton">
                      <%= form_with(url: "todos/#{todo.id}", method: "delete") do %>
                      <%= image_submit_tag("delete2.png", height: "15", width: "15") do %>
                      <% end %>
                      <% end %>
                    </a>
              </div>
            </li>
        <% end %>
      </ul>
</section>

app/views/todos/index.html.erb
<main class="TodoPageMain">
    <article>
      <h1 class="TodoPage-title">My Todo-list</h1>
      <%= form_with(url: "/todos", method: "post", class: "AddTodo") do %>
      <%= text_field_tag "todo_text", nil, class: "AddTodo-text", autofocus: true, placeholder: "What's next?" %>
      <%= date_field_tag "due_date", nil, class: "AddTodo-date" %>
      <%= submit_tag "Add", class: "AddTodo-button" %>
      <% end %>
      <%= render partial: "todo-section", locals: {
                   section_title: "Overdue",
                   todos: @todos.overdue,
                   show_due_date: true,
          
                 } %>
      <%= render partial: "todo-section", locals: {
                   section_title: "Due Today",
                   todos: @todos.due_today,
                   show_due_date: false,
          
                 } %>
      <%= render partial: "todo-section", locals: {
                   section_title: "Due Later",
                   todos: @todos.due_later,
                   show_due_date: true,
          
                 } %>


    </article>
  </main>

app/views/users/new.html.erb
<p class="NewUsers-title">Welcome new user</p>
<section class="UsersNew">
    <%= form_with(url: "/users", method: "post") do %>
        <div class="Form-section">
            <p class="Input-label">
                 First name:
            </p>
            <%= text_field_tag "first_name", nil, autofocus: true,
                                                  placeholder: "First Name",
                                                  class: "Form-Input" %>
        </div>

        <div class="Form-section">
            <p class="Input-label">
                Last name:
            </p>
            <%= text_field_tag "last_name", nil,
                               placeholder: "Last Name",
                               class: "Form-Input" %>
        </div>

        <div class="Form-section">
            <p class="Input-label">
                Email ID:
            </p>
            <%= text_field_tag "email", nil,
                               placeholder: "email",
                               class: "Form-Input" %>
        </div>

        <div class="Form-section">
            <p class="Input-label">
                Password :
            </p>
            <%= password_field_tag "password", value = nil, class: "Form-input" %>
        </div>

        <div class="Form-section">
            <%= submit_tag "Sign-up!", class: "Form-submit" %>
        </div>
    <% end %>
</section>